apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: angularimages
  name: angularimages
spec:
  selector:
    matchLabels:
      app: angularimages
  replicas: 3
  template:
    metadata:
      labels:
        app: angularimages
    spec:
      containers:
      - image: ratheeshlalukms/testimage:#{Build.BuildId}#
        name: angularimages
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: angular-service-images
spec:
  selector:
    app: angularimages
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
#   nodePort: 31000
